[project]
name = "prc-client"
version = "0.1.0"
description = "A flexible, feature-rich API client for the ER:LC private server API."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "annotated-types==0.7.0",
    "pip==26.1.2",
    "pydantic==2.13.4",
    "pydantic-core==2.46.4",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "uv==0.11.19",
]

[tool.ruff]
line-length = 120
select = ["E", "F"]
