name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up UV
        uses: astral-sh/setup-uv@v6

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish